services:
  client:
    build: client-a2
    restart: on-failure
    depends_on:
      - server
    ports:
      - "3000:3000"

  # --
  server:
    build: server-a3
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  # --
  db:
    image: mysql:latest
    volumes:
      - ./server-a3/db-dump:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: root

    # bind ports somewhere??
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=root --silent"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 30s

